<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('user/default', array('controller' => 'login', 'action' => 'process')));
$form->setAttribute('method', 'post');
?>

<div class="row">
    <div id="box" class="col-lg-3 col-centered">
        <?php echo $this->form()->openTag($form); ?>
        <div class="form-group">
            <?php
            echo $this->formLabel($form->get('user_email'));
            echo $this->formElement($form->get('user_email'));
            echo $this->formElementErrors($form->get('user_email'));
            ?>
        </div>
        <div class="form-group">
            <?php
            echo $this->formLabel($form->get('user_password'));
            echo $this->formElement($form->get('user_password'));
            echo $this->formElementErrors($form->get('user_password'));
            ?>
        </div>
        <div class="checkbox">
            <?php
            echo $this->formLabel($form->get('rememberme'));
            echo $this->formElement($form->get('rememberme'));
            echo $this->formElementErrors($form->get('rememberme'));
            ?>
        </div>
        <?php
        echo $this->formElement($form->get('submit'));
        echo $this->formElementErrors($form->get('submit'));
        ?>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>