<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', 'submit.action');
$form->setAttribute('method', 'post');
?>

<div class="row">
    <div id="box" class="col-lg-3 col-centered">
        <?php echo $this->form()->openTag($form); ?>
        <div id="system_email_div" class="form-group">
             <label id="system_email_error" class="control-label" for="system_email">Wrong user </label>
            <?php
            echo $this->formLabel($form->get('email'));
            echo $this->formElement($form->get('email'));
           // echo $this->formElementErrors($form->get('email'));
            ?>
           
            
        </div>
        <div id="system_password_div"  class="form-group">
            <label id="system_password_error" class="control-label" for="system_password">Wrong user </label>
            <?php
            echo $this->formLabel($form->get('password'));
            echo $this->formElement($form->get('password'));
          //  echo $this->formElementErrors($form->get('password'));
            ?>
            
           
           
        </div>
        <div class="checkbox">
            <?php
            echo $this->formLabel($form->get('rememberme'));
            echo $this->formElement($form->get('rememberme'));
            echo $this->formElementErrors($form->get('rememberme'));
            ?>
        </div>
        <?php
        echo $this->formElement($form->get('submit'));
        echo $this->formElementErrors($form->get('submit'));
        ?>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>
<script type="text/javascript">

    $('#loginForm').validationEngine('attach', {
        onValidationComplete: function(form, status) {

            if (status) {
                fncCheckUserLogin();
                return false;
            }
        }
    });
</script>